# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, ... }:

{
  imports =
    [ <nixpkgs/nixos/modules/installer/scan/not-detected.nix>
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  boot.initrd.luks.devices = [
    {
      name = "decrypt";
      device = "/dev/disk/by-uuid/b4a94900-321a-4ec4-ad23-b12709a90544";
      preLVM = true;
      allowDiscards = true;
    }
  ];

  fileSystems."/" =
    { device = "/dev/mapper/wn007linux-nixos";
      fsType = "ext4";
      options = [ "relatime" "discard" ];
    };

  fileSystems."/home" =
    { device = "/dev/mapper/wn007linux-home";
      fsType = "ext4";
      options = [ "relatime" "discard" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A229-6ADE";
      fsType = "vfat";
    };

  swapDevices = [ ];

  nix.maxJobs = lib.mkDefault 4;
  powerManagement.cpuFreqGovernor = lib.mkDefault "powersave";

  hardware = {
    bluetooth = {
      enable = true;
    };
  };
}
